corpus=/home/airenas/hdd/prozodija/laimis.v02a/wav/
## Acoustic models
ams=$(patsubst %,am-%,L-V01 L-V02a)
am-L-V01-dir=/home/avaiciunas/gfs/tts/espnet/egs2/laimis/tts1/v-01/exp/tts_train_fastspeech2_raw_phn_none
am-L-V01-vrs=$(patsubst %,amv-%,train.loss.ave_5best 1500epoch)

am-L-V02a-dir=/home/avaiciunas/gfs/tts/espnet/egs2/laimis/tts1/v-02a/exp/tts_train_fastspeech2_raw_phn_none
am-L-V02a-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best 1500epoch)

## Vocoders
vocs=$(patsubst %,voc-%,L-V02aStyle L-V01Style)
voc-L-V02aStyle-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/laimis/voc1/exp/train_nodev_ljspeech_style_melgan.v1
voc-L-V02aStyle-vrs=$(patsubst %,vocv-%,500000 1000000)

voc-L-V01Style-dir=/home/avaiciunas/.cache/parallel_wavegan/laimis.style.1500000-01
voc-L-V01Style-vrs=$(patsubst %,vocv-%,2000000)
