corpus=/home/airenas/hdd/prozodija/vytautas.v05/wav/
## Acoustic models
ams=$(patsubst %,am-%,V06b)
am-V02-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-02/exp/tts_train_fastspeech2_raw_phn_none
am-V02-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-SB-dir=/home/avaiciunas/.cache/espnet/p03/p-03/exp/tts_train_fastspeech2_raw_phn_none
am-SB-vrs=$(patsubst %,amv-%,train.loss.ave_5best)

am-V03a-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-03a/exp/tts_train_fastspeech2_raw_phn_none
am-V03a-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-V03b-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-03b/exp/tts_train_fastspeech2_raw_phn_none
am-V03b-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-V04-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-04/exp/tts_train_fastspeech2_raw_phn_none
am-V04-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-V05b-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-05b/exp/tts_train_fastspeech2_raw_phn_none
am-V05b-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best 1000epoch)

am-V05-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-05/exp/tts_train_fastspeech2_raw_phn_none
am-V05-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best 1000epoch)

am-V05a-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-05a/exp/tts_train_fastspeech2_raw_phn_none
am-V05a-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best 1000epoch)

am-V06b-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-06b/exp/tts_train_fastspeech2_raw_phn_none
am-V06b-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best 1500epoch)

## Vocoders
vocs=$(patsubst %,voc-%,V06bStyle)

voc-V06bStyle-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/exp/train_nodev_ljspeech_style_melgan.v1
voc-V06bStyle-vrs=$(patsubst %,vocv-%,100000)
