corpus=/home/airenas/hdd/prozodija/vytautas.v05/wav/
## Acoustic models
ams=$(patsubst %,am-%,V02 SB V03a V04 V03b V05b V05 V05a)
am-V02-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-02/exp/tts_train_fastspeech2_raw_phn_none
am-V02-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-SB-dir=/home/avaiciunas/.cache/espnet/p03/p-03/exp/tts_train_fastspeech2_raw_phn_none
am-SB-vrs=$(patsubst %,amv-%,train.loss.ave_5best)

am-V03a-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-03a/exp/tts_train_fastspeech2_raw_phn_none
am-V03a-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-V03b-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-03b/exp/tts_train_fastspeech2_raw_phn_none
am-V03b-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-V04-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-04/exp/tts_train_fastspeech2_raw_phn_none
am-V04-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-V05b-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-05b/exp/tts_train_fastspeech2_raw_phn_none
am-V05b-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best)

am-V05-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-05/exp/tts_train_fastspeech2_raw_phn_none
am-V05-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best 1000epoch)

am-V05a-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-05a/exp/tts_train_fastspeech2_raw_phn_none
am-V05a-vrs=$(patsubst %,amv-%,train.loss.ave_5best valid.loss.ave_5best 1000epoch)

## Vocoders
vocs=$(patsubst %,voc-%,V02 LJ SB V02HiFi V03a V05Style V05)
voc-V02-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/v02/exp/train_nodev_ljspeech_parallel_wavegan.v3
voc-V02-vrs=$(patsubst %,vocv-%,1000000 2000000 3000000 2500000 500000)

voc-LJ-dir=/home/avaiciunas/.cache/parallel_wavegan/ljspeech_parallel_wavegan.v1
voc-LJ-vrs=$(patsubst %,vocv-%,400000)

voc-SB-dir=/home/avaiciunas/.cache/parallel_wavegan/sabina.pwg.01-700000
voc-SB-vrs=$(patsubst %,vocv-%,700000)

voc-V02HiFi-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/hf
voc-V02HiFi-vrs=$(patsubst %,vocv-%,10000 500000 900000 1000000)

voc-V03a-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/v03a
voc-V03a-vrs=$(patsubst %,vocv-%,200000 450000 800000)

voc-V05Style-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/style
voc-V05Style-vrs=$(patsubst %,vocv-%,350000)

voc-V05-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/exp/train_nodev_ljspeech_parallel_wavegan.v3
voc-V05-vrs=$(patsubst %,vocv-%,195000)
