corpus=/home/airenas/hdd/prozodija/vytautas.v04/wav/
## Acoustic models
ams=$(patsubst %,am-%,V02 SB V03a V04 V03b)
am-V02-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-02/exp/tts_train_fastspeech2_raw_phn_none
am-V02-vrs=$(patsubst %,amv-%,1000epoch train.loss.ave_5best valid.loss.ave_5best 976epoch 84epoch)

am-SB-dir=/home/avaiciunas/.cache/espnet/p03/p-03/exp/tts_train_fastspeech2_raw_phn_none
am-SB-vrs=$(patsubst %,amv-%,train.loss.ave_5best)

am-V03a-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-03a/exp/tts_train_fastspeech2_raw_phn_none
am-V03a-vrs=$(patsubst %,amv-%,1000epoch train.loss.ave_5best valid.loss.ave_5best 997epoch 288epoch)

am-V03b-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-03b/exp/tts_train_fastspeech2_raw_phn_none
am-V03b-vrs=$(patsubst %,amv-%,430epoch)

am-V04-dir=/home/avaiciunas/gfs/tts/espnet/egs2/vytautas/tts1/v-04/exp/tts_train_fastspeech2_raw_phn_none
am-V04-vrs=$(patsubst %,amv-%,1000epoch train.loss.ave_5best valid.loss.ave_5best 197epoch)

## Vocoders
vocs=$(patsubst %,voc-%,V02 LJ SB V02HiFi V03a)
voc-V02-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/v02/exp/train_nodev_ljspeech_parallel_wavegan.v3
voc-V02-vrs=$(patsubst %,vocv-%,1000000 2000000 3000000 2010000 1990000 1500000 2500000 500000)

voc-LJ-dir=/home/avaiciunas/.cache/parallel_wavegan/ljspeech_parallel_wavegan.v1
voc-LJ-vrs=$(patsubst %,vocv-%,400000)

voc-SB-dir=/home/avaiciunas/.cache/parallel_wavegan/sabina.pwg.01-700000
voc-SB-vrs=$(patsubst %,vocv-%,700000)

voc-V02HiFi-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/hf
voc-V02HiFi-vrs=$(patsubst %,vocv-%,10000 110000 500000 600000 700000)

voc-V03a-dir=/home/avaiciunas/gfs/tts/ParallelWaveGAN/egs/vytautas/voc1/exp/train_nodev_ljspeech_parallel_wavegan.v3
voc-V03a-vrs=$(patsubst %,vocv-%,100000 200000 450000 540000)
